apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: simple-nodejs-app-nxfi
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: simple-nodejs-app-nxfi
    app.kubernetes.io/part-of: nodejs-users
  name: simple-nodejs-app-nxfi
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: simple-nodejs-app-nxfi
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: simple-nodejs-app-nxfi
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-fnvs-tenant/nodejs-users/simple-nodejs-app-nxfi@sha256:67d2e66da3b04ff292de738f9a196082a778c3999b8cb90b9ae2a330e5cd6b98
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
